# Generated by Django 4.2.4 on 2023-08-27 05:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="n/a", max_length=200)),
                ("primary_color", models.CharField(default="n/a", max_length=50)),
                ("secondary_color", models.CharField(default="n/a", max_length=50)),
                (
                    "heat_index",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="heat_index",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_color",
            field=models.CharField(default="n/a", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="secondary_color",
            field=models.CharField(default="n/a", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/default.jpg", upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="n/a", max_length=200),
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="n/a", max_length=200)),
                (
                    "similar_items",
                    models.ManyToManyField(
                        related_name="styles", to="home.similaritem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="similar_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.similaritem",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="styles",
            field=models.ManyToManyField(related_name="products", to="home.style"),
        ),
    ]
