# Generated by Django 4.2.4 on 2023-08-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_similaritem_image_alter_product_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("shoes", "Shoes"),
                    ("accessory", "Accessory"),
                ],
                default="top",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="similaritem",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("shoes", "Shoes"),
                    ("accessory", "Accessory"),
                ],
                default="top",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="secondary_color",
            field=models.CharField(
                choices=[
                    ("n/a", "None"),
                    ("black", "Black"),
                    ("grey", "Grey"),
                    ("white", "White"),
                    ("maroon", "Maroon"),
                    ("red", "Red"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("orange", "Orange"),
                    ("apricot", "Apricot"),
                    ("olive", "Olive"),
                    ("yellow", "Yellow"),
                    ("beige", "Beige"),
                    ("lime", "Lime"),
                    ("green", "Green"),
                    ("mint", "Mint"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                    ("navy", "Navy"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("lavender", "Lavender"),
                    ("magenta", "Magenta"),
                ],
                default="black",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="similaritem",
            name="secondary_color",
            field=models.CharField(
                choices=[
                    ("n/a", "None"),
                    ("black", "Black"),
                    ("grey", "Grey"),
                    ("white", "White"),
                    ("maroon", "Maroon"),
                    ("red", "Red"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("orange", "Orange"),
                    ("apricot", "Apricot"),
                    ("olive", "Olive"),
                    ("yellow", "Yellow"),
                    ("beige", "Beige"),
                    ("lime", "Lime"),
                    ("green", "Green"),
                    ("mint", "Mint"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                    ("navy", "Navy"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("lavender", "Lavender"),
                    ("magenta", "Magenta"),
                ],
                default="n/a",
                max_length=50,
            ),
        ),
    ]
