# Generated by Django 4.2.4 on 2023-08-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_product_formality_alter_similaritem_formality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
