# Generated by Django 4.2.4 on 2023-08-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_product_formality_alter_similaritem_formality"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="belt",
            field=models.BooleanField(default=False),
        ),
    ]
