# Generated by Django 4.2.4 on 2023-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_product_belt"),
    ]

    operations = [
        migrations.AddField(
            model_name="similaritem",
            name="belt",
            field=models.BooleanField(default=False),
        ),
    ]
