# Generated by Django 4.2.4 on 2023-08-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_product_primary_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="styles",
            field=models.ManyToManyField(
                default=None, related_name="products", to="home.style"
            ),
        ),
    ]
