# Generated by Django 4.2.4 on 2023-08-31 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_product_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="similar_item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.similaritem",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="styles",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="home.style"
            ),
        ),
    ]
