# Generated by Django 4.2.4 on 2023-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_product_similar_item_alter_product_styles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="products/default.png", upload_to="products/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="similaritem",
            name="photos",
            field=models.ManyToManyField(blank=True, to="home.photo"),
        ),
    ]
