# Generated by Django 4.2.4 on 2023-09-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_photo_similaritem_photos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="similaritem",
            old_name="photos",
            new_name="fits",
        ),
    ]
