# Generated by Django 5.0.1 on 2024-08-29 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=200)),
                ('image', models.ImageField(default='outfits/default.png', upload_to='outfits/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('primary_color', models.CharField(choices=[('#000000', 'Black'), ('#808080', 'Grey'), ('#FFFFFF', 'White'), ('#800000', 'Maroon'), ('#FF0000', 'Red'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#FFA500', 'Orange'), ('#FBCEB1', 'Apricot'), ('#808000', 'Olive'), ('#FFFF00', 'Yellow'), ('#F5F5DC', 'Beige'), ('#00FF00', 'Lime'), ('#008000', 'Green'), ('#98FB98', 'Mint'), ('#008080', 'Teal'), ('#00FFFF', 'Cyan'), ('#000080', 'Navy'), ('#0000FF', 'Blue'), ('#800080', 'Purple'), ('#E6E6FA', 'Lavender'), ('#FF00FF', 'Magenta')], default='black', max_length=50)),
                ('secondary_color', models.CharField(choices=[('n/a', 'None'), ('#000000', 'Black'), ('#808080', 'Grey'), ('#FFFFFF', 'White'), ('#800000', 'Maroon'), ('#FF0000', 'Red'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#FFA500', 'Orange'), ('#FBCEB1', 'Apricot'), ('#808000', 'Olive'), ('#FFFF00', 'Yellow'), ('#F5F5DC', 'Beige'), ('#00FF00', 'Lime'), ('#008000', 'Green'), ('#98FB98', 'Mint'), ('#008080', 'Teal'), ('#00FFFF', 'Cyan'), ('#000080', 'Navy'), ('#0000FF', 'Blue'), ('#800080', 'Purple'), ('#E6E6FA', 'Lavender'), ('#FF00FF', 'Magenta')], default='black', max_length=50)),
                ('formality', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('heat_index', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('belt', models.BooleanField(default=False)),
                ('styles', models.ManyToManyField(blank=True, related_name='outfits', to='home.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
